Add fall through comment to appease ErrorProne
Compiling with error prone (the default with Bazel) complains because one of the case doesn't have "fall-through".

```
StringBase64Decoder.java:152: error: [FallThrough] Execution may fall through from the previous case; add a `// fall through` comment before this line if it was deliberate
            case STATE_OUTPUT_3:
            ^
    (see http://errorprone.info/bugpattern/FallThrough)
```